"""Embed the Remotion fonts in the JS bundle as base64, subset to Latin.

Why: loading fonts over the render server's HTTP hung on long renders (a tab
waited 118s for "Loading fonts" at frame 5144 and killed a 13-minute render).
Fonts compiled into the bundle need no request at all.

Only needed again if you change a font in remotion/src/fonts/. Needs fonttools
(dev-only, not in requirements.txt):

    pip install fonttools
    python tools/embed_fonts.py
"""

from __future__ import annotations

import base64
import io
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

FONTS_DIR = Path(__file__).resolve().parent.parent / "remotion" / "src" / "fonts"
# Latin, Latin-1, general punctuation, currency - everything a US/UK finance script uses.
UNICODES = "U+0020-007E,U+00A0-00FF,U+2010-2027,U+2030-203A,U+20AC,U+2122,U+2190-2193,U+2212"
FONTS = {"OSWALD": "Oswald.ttf", "INTER": "Inter.ttf", "SOURCE_SERIF": "SourceSerif4.ttf"}


def subset_font(path: Path) -> bytes:
    font = TTFont(path)
    options = subset.Options()
    options.layout_features = ["*"]
    subsetter = subset.Subsetter(options)
    subsetter.populate(unicodes=subset.parse_unicodes(UNICODES))
    subsetter.subset(font)
    buffer = io.BytesIO()
    font.save(buffer)
    return buffer.getvalue()


def main() -> None:
    lines = ["// GENERATED by tools/embed_fonts.py - do not edit. Latin subsets, base64 TTF.", ""]
    for name, file in FONTS.items():
        data = subset_font(FONTS_DIR / file)
        lines.append(f'export const {name} = "data:font/ttf;base64,{base64.b64encode(data).decode()}";')
        print(f"{file}: {(FONTS_DIR / file).stat().st_size // 1024} KB -> {len(data) // 1024} KB")
    (FONTS_DIR / "embedded.ts").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
